apiVersion: v1
kind: Namespace
metadata:
  name: rbac-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: rbac-dev
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: rbacaws/api-gateway:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
            - name: debug
              containerPort: 9229
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: API_GATEWAY_PORT
              value: "3000"
            - name: AUTH_SERVICE_HOST
              value: "auth-service"
            - name: RBAC_CORE_HOST
              value: "rbac-core"
            - name: AUDIT_LOG_SERVICE_HOST
              value: "audit-log-service"
          volumeMounts:
            - name: route-mappings-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: route-mappings-volume
          configMap:
            name: route-mappings
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rbac-dev
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: debug
      port: 9229
      targetPort: 9229
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: rbac-dev
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rbacaws/auth-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3200
            - name: debug
              containerPort: 9229
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: AUTH_SERVICE_PORT
              value: "3200"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: rbac-dev
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: debug
      port: 9229
      targetPort: 9229
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-core
  namespace: rbac-dev
  labels:
    app: rbac-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-core
  template:
    metadata:
      labels:
        app: rbac-core
    spec:
      containers:
        - name: rbac-core
          image: rbacaws/rbac-core:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3100
            - name: debug
              containerPort: 9229
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: RBAC_CORE_PORT
              value: "3100"
---
apiVersion: v1
kind: Service
metadata:
  name: rbac-core
  namespace: rbac-dev
spec:
  selector:
    app: rbac-core
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: debug
      port: 9229
      targetPort: 9229
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-log-service
  namespace: rbac-dev
  labels:
    app: audit-log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-log-service
  template:
    metadata:
      labels:
        app: audit-log-service
    spec:
      containers:
        - name: audit-log-service
          image: rbacaws/audit-log-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3300
            - name: debug
              containerPort: 9229
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: AUDIT_LOG_SERVICE_PORT
              value: "3300"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-log-service
  namespace: rbac-dev
spec:
  selector:
    app: audit-log-service
  ports:
    - name: http
      port: 3300
      targetPort: 3300
    - name: debug
      port: 9229
      targetPort: 9229
  type: ClusterIP
