apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbac-local
  namespace: rbac-dev
spec:
  ingressClassName: nginx
  rules:
    - host: rbac.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
