kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Map host ports 80/443 to the kind node's stable NodePorts 30080/30443.
      # Ensure the ingress-nginx controller Service uses nodePort 30080 (http) and 30443 (https).
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
